server:
    port: 8080

spring:
    application:
        name: payment-wechat

    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8

    datasource:
        url: jdbc:mysql://127.0.0.1:3306/payment_wechat?allowMultiQueries=true&useUnicode=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&autoReconnect=true&nullCatalogMeansCurrent=true
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource

        druid:
            web-stat-filter:
                enabled: true
            stat-view-servlet:
                enabled: true
                # 设置白名单，不填则允许所有访问
                allow:
                url-pattern: /druid/*
                # 控制台管理用户名和密码
                login-username:
                login-password:
            filter:
                stat:
                    enabled: true
                    # 慢 SQL 记录
                    log-slow-sql: true
                    slow-sql-millis: 100
                    merge-sql: true
                wall:
                    config:
                        multi-statement-allow: true

mybatis-plus:
    configuration:
        log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl

    global-config:
        banner: false

--- #==================== swagger 相关配置 ====================#

web:
    base-package: com.github.payment
    api-prefix: /api

--- #==================== swagger 相关配置 ====================#

swagger:
    title: 微信支付示例项目
    description: 基于spring-boot的微信支付案例项目
    version: 1.0.0
    base-package: ${web.base-package}

--- #==================== 微信支付相关配置 ====================#

wxpay:
    # 商户号
    mch-id: 1558950191
    # 商户API证书序列号
    mch-serial-no: 34345964330B66427E0D3D28826C4993C77E631F
    # 商户私钥文件
    private-key-path: apiclient_key.pem
    # APIv3密钥
    api-v3-key: UDuLFDcmy5Eb6o0nTNZdu6ek4DDh4K8B
    # APPID
    appid: wx74862e0dfcf69954
    # 微信服务器地址
    domain: https://api.mch.weixin.qq.com
    # 接收结果通知地址
    notify-domain: https://7f15-123-139-165-92.jp.ngrok.io

logging:
    level:
        com.github: debug


